param(
    [string] $SourceRoot = 'C:\Program Files (x86)\SCHNAIL Client',
    [string] $AssetRoot = ''
)

$ErrorActionPreference = 'Stop'

$repo = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
if ([string]::IsNullOrWhiteSpace($AssetRoot)) {
    $AssetRoot = Join-Path $repo 'data'
}

$source = (Resolve-Path -LiteralPath $SourceRoot).Path
$target = [System.IO.Path]::GetFullPath($AssetRoot)
$repoWithSlash = $repo.TrimEnd('\') + '\'
if (-not ($target.StartsWith($repoWithSlash, [System.StringComparison]::OrdinalIgnoreCase))) {
    throw "AssetRoot must be inside the repository. repo=$repo target=$target"
}

$required = @(
    'bots\bots.dat',
    'maps\maps.dat',
    'res\sc_hotkeys.csv',
    'res\hotkey_data\stat_txt.txt',
    'res\hotkey_data\sctblcmp.exe',
    'schnail-client.exe'
)

foreach ($relative in $required) {
    $path = Join-Path $source $relative
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Required source asset was not found: $path"
    }
}

function Sync-Directory {
    param(
        [Parameter(Mandatory = $true)] [string] $From,
        [Parameter(Mandatory = $true)] [string] $To
    )

    $fullTo = [System.IO.Path]::GetFullPath($To)
    $targetWithSlash = $target.TrimEnd('\') + '\'
    if (-not ($fullTo.StartsWith($targetWithSlash, [System.StringComparison]::OrdinalIgnoreCase))) {
        throw "Refusing to mirror outside AssetRoot: $fullTo"
    }

    New-Item -ItemType Directory -Force -Path $fullTo | Out-Null
    & robocopy $From $fullTo /MIR /R:2 /W:1 /NFL /NDL /NJH /NJS /NP | Out-Null
    if ($LASTEXITCODE -gt 7) {
        throw "robocopy failed with exit code $LASTEXITCODE from '$From' to '$fullTo'"
    }
}

New-Item -ItemType Directory -Force -Path $target | Out-Null
Sync-Directory (Join-Path $source 'bots') (Join-Path $target 'bots')
Sync-Directory (Join-Path $source 'maps') (Join-Path $target 'maps')
Sync-Directory (Join-Path $source 'res\hotkey_icons') (Join-Path $target 'res\hotkey_icons')
Sync-Directory (Join-Path $source 'res\hotkey_data') (Join-Path $target 'res\hotkey_data')

New-Item -ItemType Directory -Force -Path (Join-Path $target 'res') | Out-Null
Copy-Item -LiteralPath (Join-Path $source 'res\sc_hotkeys.csv') -Destination (Join-Path $target 'res\sc_hotkeys.csv') -Force
if (Test-Path -LiteralPath (Join-Path $source 'res\messages_kr.properties')) {
    Copy-Item -LiteralPath (Join-Path $source 'res\messages_kr.properties') -Destination (Join-Path $target 'res\messages_kr.properties') -Force
}

$mpqToolRoot = Join-Path $target 'tools\mpq'
New-Item -ItemType Directory -Force -Path $mpqToolRoot | Out-Null
Copy-Item -LiteralPath (Join-Path $source 'schnail-client.exe') -Destination (Join-Path $mpqToolRoot 'schnail-client.exe') -Force

$readme = @"
# StarAI Bundled Assets

This folder is owned by StarAI Practice Client at runtime.
It is generated by scripts/import-schnail-assets.ps1 from a local SCHNAIL install during release preparation.
The application reads this folder directly and does not require SCHNAIL to be installed on the end-user machine.
"@
Set-Content -LiteralPath (Join-Path $target 'README.md') -Value $readme -Encoding UTF8

$botCount = (Get-ChildItem -LiteralPath (Join-Path $target 'bots') -Directory | Measure-Object).Count
$mapCount = (Get-ChildItem -LiteralPath (Join-Path $target 'maps') -File | Measure-Object).Count
$bytes = (Get-ChildItem -LiteralPath $target -Recurse -File | Measure-Object Length -Sum).Sum
Write-Host "import-schnail-assets: target=$target bots=$botCount mapFiles=$mapCount bytes=$bytes"
